# Build a docker image of the e2e tests and push it to the azure docker registry.
#
name: Create docker image
run-name: Create docker image (${{ github.event_name }})
on:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: [self-hosted, Linux, X64, obscuro-test-gh-runner-01]
    steps:
      - name: 'Check out obscuro-test'
        uses: actions/checkout@v3
        with:
          path: ./obscuro-test

      - name: 'Check out go-obscuro code'
        uses: actions/checkout@v3
        with:
          repository: obscuronet/go-obscuro
          path: ./go-obscuro

      - name: 'Login to Azure docker registry'
        uses: azure/docker-login@v1
        with:
          login-server: testnetobscuronet.azurecr.io
          username: testnetobscuronet
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: 'Build the docker container'
        run: |
          cd ${{ github.workspace }}/obscuro-test
          ./get_artifacts.sh
          docker build -t obscuronet/obscuro_test:latest -f ./utils/docker/image.Dockerfile .  
          docker push obscuronet/obscuro_test:latest
