# Resets the nonce persistence and redeploys the set of persisted contracts that should persist on a
# given network before being redeployed. The workflow is run manually from a workflow dispatch.
#
name: Reset persistence
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: testnet
        options:
          - testnet
          - dev-testnet

jobs:
  reset-persistence:
    runs-on: self-hosted
    steps:
      - name: 'Check out obscuro-test'
        uses: actions/checkout@v3
        with:
          path: ./obscuro-test
          token: ${{ secrets.GH_COMMIT_PAT }}

      - name: 'Update the workflow details'
        run: |
          cd ${{ github.workspace }}/obscuro-test
          echo Date: `date` > .workflow
          echo Run ID: ${{ github.run_id }} >> .workflow
          echo Run Attempt: ${{ github.run_attempt }} >> .workflow
          git config user.name "Moray Grieve"
          git config user.email "moray.grieve@me.com"
          git add .workflow
          git commit -m "Reset persistence run ID ${{ github.run_id}}"
          git push origin ${{ github.ref }}

      - name: 'Check out go-obscuro code'
        uses: actions/checkout@v3
        with:
          repository: obscuronet/go-obscuro
          path: ./go-obscuro

      - name: 'Build artifacts'
        run: |
          cd ${{ github.workspace }}/go-obscuro/tools/walletextension/main
          go build -o ${{ github.workspace }}/obscuro-test/artifacts/wallet_extension/wallet_extension
          ls -l ${{ github.workspace }}/obscuro-test/artifacts

      - name: 'Persistence reset on testnet'
        if: ${{ github.event.inputs.environment == 'testnet' }}
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run persistence_reset

      - name: 'Persistence reset on dev-testnet'
        if: ${{ github.event.inputs.environment == 'dev-testnet' }}
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run -m obscuro.dev persistence_reset

      - name: 'Upload output'
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifact
          path: |
            ${{ github.workspace }}/obscuro-test/**/Output
          retention-days: 2