# Run tests on a new deployment or upgrade of testnet or dev-testnet. The workflow is only triggered on a repository
# dispatch sent by the deployment of the faucet. For dev-testnet full tests will be run with a persistence if a new
# deployment. For testnet only a persistence reset will be performed on a new deployment.
#
name: Run deploy tests
run-name: Run deploy tests (${{ github.event.action }})
on:
  repository_dispatch:
    types: [ faucet_testnet_deployed, faucet_testnet_upgraded, faucet_dev_testnet_deployed, faucet_dev_testnet_upgraded ]

jobs:
  test-run:
    runs-on: self-hosted
    steps:
      - run: echo "Triggered by ${{ github.event_name }}"
      - run: echo "Action       ${{ github.action }}"
      - run: echo "Branch       ${{ github.ref }}"

      - name: 'Check out obscuro-test'
        uses: actions/checkout@v3
        with:
          path: ./obscuro-test
          token: ${{ secrets.GH_COMMIT_PAT }}

      - name: 'Update the workflow details'
        run: |
          cd ${{ github.workspace }}/obscuro-test
          echo Date: `date` > .workflow
          echo Run ID: ${{ github.run_id }} >> .workflow
          echo Run Attempt: ${{ github.run_attempt }} >> .workflow
          git config user.name "Moray Grieve"
          git config user.email "moray.grieve@me.com"
          git add .workflow
          git commit -m "Update workflow run details"
          git push origin ${{ github.ref }}

      - name: 'Check out go-obscuro code'
        uses: actions/checkout@v3
        with:
          repository: obscuronet/go-obscuro
          path: ./go-obscuro

      - name: 'Build required artifacts for running tests'
        run: |
          cd ${{ github.workspace }}/obscuro-test
          ./get_artifacts.sh
          ls -l ${{ github.workspace }}/obscuro-test/artifacts   

      - name: 'Run tests on dev-testnet on a repository_dispatch trigger of a new deployment'
        if: ${{ (github.event_name == 'repository_dispatch') && (github.event.action == 'faucet_dev_testnet_deployed') }}
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run -m obscuro.dev persistence_reset
          cd ${{ github.workspace }}/obscuro-test/tests
          /usr/local/bin/pysys.py run -m obscuro.dev -r -e skip -e robustness -e performance

      - name: 'Run tests on dev-testnet on a repository_dispatch trigger of an upgrade'
        if: ${{ (github.event_name == 'repository_dispatch') && (github.event.action == 'faucet_dev_testnet_upgraded') }}
        run: |
          cd ${{ github.workspace }}/obscuro-test/tests
          /usr/local/bin/pysys.py run -m obscuro.dev -r -e skip -e robustness -e performance

      - name: 'Run tests on testnet on a repository_dispatch trigger of a new deployment'
        if: ${{ (github.event_name == 'repository_dispatch') && (github.event.action == 'faucet_testnet_deployed') }}
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run persistence_reset

      - name: 'Upload testcase output'
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifact
          path: |
            ${{ github.workspace }}/obscuro-test/**/Output
          retention-days: 2

      - name: 'Test report'
        uses: dorny/test-reporter@v1
        if: always()
        with:
          working-directory: ${{ github.workspace }}/obscuro-test/
          name: 'test-report'
          path: 'reports/*.xml'
          reporter: java-junit
          fail-on-error: 'false'
          only-summary: 'true'